name: Java Tests with Maven and Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v3

      - name: Java 8 kur
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Maven ile testleri çalıştır
        run: mvn clean test -Dsurefire.useFile=false

      - name: Allure sonuç klasörünü kontrol et
        run: ls -la target/allure-results || echo "allure-results not found"

      - name: Allure raporlarını üret
        run: mvn allure:report -Dallure.results.directory=target/allure-results


      - name: Allure raporunu yayınla
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
